    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{form_data['topic']} - Technical Report</title>
    <style>
        @page {{ size: A4; margin: 1cm 1cm 2cm 2cm; }}
        body {{
            font-family: 'Times New Roman', serif;
            font-size: 12pt;
            line-height: 1.6;
            color: #000;
            max-width: 180mm;
            margin: 0 auto;
            padding: 1cm 1cm 2cm 2cm;
        }}
        .cover {{
            text-align: center;
            padding-top: 0;
            page-break-after: always;
            page-break-inside: avoid;
        }}
        .cover-logo {{
            margin-bottom: 0.5cm;
        }}
        .cover-logo img {{
            height: 200px;
        }}
        .cover h1 {{
            font-size: 26pt;
            font-weight: bolder;
            margin: 1.5cm 0 0.8cm 0;
            border-bottom: none;
            padding-bottom: 0;
        }}
        .cover .meta {{
            font-size: 14pt;
            margin: 0.2cm 0;
        }}
        .cover .meta-subtitle {{
            font-size: 22pt;
            font-weight: lighter;
        }}
        .cover .meta-prepared {{
            font-size: 20pt;
            font-weight: lighter;
            font-style: italic;
            margin-top: 2cm;
        }}
        .cover .meta-author {{
            font-size: 22pt;
            font-weight: bold;
            font-style: normal;
            margin-top: 0cm;
        }}
         .cover .meta-institution {{
            white-space: nowrap;      
            overflow: hidden;       
            /* text-overflow: ellipsis;    */
            /* max-width: 300px; */
            font-size: 19pt;
            font-weight: lighter;
            margin-top: 1cm;
        }}
       .cover .meta-footer {{
            font-size: 18pt;
            font-weight: lighter;
            margin-top: 3cm;
            color: green;
        }}
        h1 {{
            font-size: 18pt;
            font-style: normal;
            margin-top: 0.5in;
            border-bottom: 2px solid #333;
            padding-bottom: 0.1in;
            page-break-after: avoid;
        }}
        h2 {{
            font-size: 14pt;
            margin-top: 0.3in;
            font-weight: bold;
            page-break-after: avoid;
        }}
        p {{
            text-align: justify;
            margin: 0.15in 0;
        }}
        .abstract {{
            font-style: italic;
            margin: 0.25in 0.5in;
        }}
        .references {{
            page-break-before: always;
        }}
        .ref-item {{
            margin: 0.15in 0;
            font-size: 10pt;
            line-height: 1.4;
            word-wrap: break-word;
            overflow-wrap: break-word;
        }}
        .ref-item a {{
            color: #0066CC;
            text-decoration: none;
            word-break: break-all;
        }}
        .ref-item a:hover {{
            text-decoration: underline;
        }}
        .tier-label {{
            font-size: 9pt;
            color: #666;
            font-weight: bold;
        }}
        .verification-panel {{
            background: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 1rem;
            margin: 1rem 0;
            font-size: 10pt;
            page-break-inside: avoid;
        }}
        .specs-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 0.5rem;
            font-size: 9pt;
        }}
        .violation {{
            background: #f8d7da;
            padding: 0.3rem;
            margin: 0.2rem 0;
            border-radius: 0.2rem;
            font-size: 9pt;
        }}
    </style>
</head>
<body>
    <div class="cover">
        <div class="cover-logo">
            {logo_html}
        </div>
        <h1>{form_data['topic']}</h1>
        
        <div class="meta meta-subtitle">
            {form_data['subject']}</div>
        <div class="meta meta-prepared">
            Prepared by:<br>
        <div class="meta meta-author">
            {form_data['researcher']}<br>
            
         <div class="meta meta-institution">
           {form_data['institution']}<br>
            {report_date}<br>
        </div>
        <div class="meta meta-footer">
            Generated by SROrch
        </div>
    </div>